### PR TITLE
Ghost-write grant section

### PR DESCRIPTION
**Pull request by reesericci**
I wrote up a section about grant money!

### CODE REVIEW

**Comment by quackduck** [comment]
I believe @bellesea's writing this section in another PR

**Comment by reesericci** [comment]
lmfao missed that one

**Comment by quackduck** [comment]
You can coordinate on #5

**Comment by sampoder** [comment]
it'd be really nice if we could include a bit from Reese about his experience with HackAustin!

**Comment by quackduck** [comment]
Definitely! @reesericci can you mention this in #5?

**Comment by quackduck** [comment]
Hmm. Although, we do want the commit to show up as from Reese. Maybe we can wait for #5 to be merged and then add in Reese's quote. This PR can be used to work on that part.

**Comment by reesericci** [comment]
Whoa not rip my PR!

**Comment by sampoder** [comment]
Reese can co-author the commit.

**Comment by quackduck** [comment]
Unfamiliar with PRs that have multiple authors. How would it work?

**Comment by quackduck** [comment]
Oh wait do you just include the co-authored line in the commit msg

**Comment by reesericci** [comment]
I don't know what I would be able to add though about my experience considering the event hasn't happened yet. I also haven't received the grant, and only received minimal donations, so I can't attest much about Bank. Although I do like the Google Workspace stuff and some of the other perks. Maybe @maggie-j-liu would have more to add?

**Pull request closed without merging**
