### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by InternetRamen**

### CODE REVIEW

**Comment by quackduck** [comment]
wait. what fun puzzles?

**Comment by InternetRamen** [comment]
Like scramble or trivia 
image

**Comment by quackduck** [comment]
Oh we want something hack club related tho. this is the hack club newsletter

**Comment by quackduck** [comment]
This would count if it was really popular among HCers

**Comment by InternetRamen** [comment]
idk like hackclub/coding related puzzles

**Pull request closed without merging**
