### PR TITLE
First Draft of My Assemble Paragraph

### PR DESCRIPTION
**Pull request by sampoder**
@quackduck, I'm not 100% of the way there. Would really appreciate some feedback!

### CODE REVIEW

**Comment by quackduck** [comment]
Brilliant summary! Would like some images (maybe 2) and maybe split into a couple paras. Feel free to use emojis and emphasis (**bold**, *italic*)

**Comment by quackduck** [comment]
I love those images

**Comment by sampoder** [comment]
GTM?

**Comment by quackduck** [comment]
I think it needs some ✨ emojis ✨

The end of that section feels not enthusiastic enough rn.

**Comment by quackduck** [comment]
okay looks great!! merging, and thanks for writing this :)

**Pull request merged**
