### PR TITLE
Hacker News

### PR DESCRIPTION
**Pull request by reesericci**
but it's not

@quackduck

### CODE REVIEW

**Comment by quackduck** [comment]
LOL.

**Comment by quackduck** [comment]
huh i though github had a new close with reason feature

**Comment by reesericci** [comment]
closing?

**Comment by reesericci** [comment]
that's illegal

**Comment by reesericci** [comment]
it's the best name

**Comment by reesericci** [comment]
i legitmately am submitting this. just like how competed in the"Stupid Shit Nobody Needs" hackathon

**Comment by reesericci** [comment]
and yes that's a logical fallacy https://yourlogicalfallacyis.com/ad-hominem

**Comment by reesericci** [comment]
Why are you closing this? It's a legit submission

**Comment by quackduck** [comment]
nahhhhhh

**Comment by reesericci** [comment]
why?

**Comment by quackduck** [comment]
I don't think we want the name of the Hack Club newsletter to refer to another publication

**Pull request closed without merging**
